// See https://svelte.dev/docs/kit/types#app.d.ts
// for information about these interfaces

// Cloudflare secrets (not auto-generated by wrangler types)
interface Env {
	GITHUB_TOKEN: string;
	CLOUDFLARE_API_KEY: string;
	CLOUDFLARE_EMAIL: string;
	CLOUDFLARE_ZONE_ID: string;
}

declare global {
	namespace App {
		interface Platform {
			env: Env;
			ctx: ExecutionContext;
			caches: CacheStorage;
			cf?: IncomingRequestCfProperties;
		}

		// interface Error {}
		// interface Locals {}
		// interface PageData {}
		// interface PageState {}
		// interface Platform {}
	}
}

export {};
